site_name: Chris Wiki
site_description: Help in case of emergency
site_author: Chris Huang

repo_url: https://github.com/cvarta/wiki.git
nav:
  - Home: index.md
  - Linux:
    - Bash:
        -  File Handling: linux/bash/file-handling.md
    - BTRFS:
      - Overview: linux/btrfs/intro.md
    - Ubuntu:
      - Initial Setup: linux/ubuntu/initial-setup.md
#theme: readthedocs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    scheme: default
#    primary: blue
#    accent: blue

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg